name: Build and Deploy Preview

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    ENVIRONMENT_NAME: preview

jobs:
    BuildAndTestFrontend:
        name: Build and Test Frontend
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        outputs:
            should-deploy: ${{ github.event_name == 'push' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

    DeployFrontendToS3:
        name: Deploy Frontend to S3
        needs: BuildAndTestFrontend
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.PREVIEW_AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.PREVIEW_AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Enable Corepack
              run: corepack enable

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Fetch Environment Variables from SSM
              id: fetch_ssm
              run: |
                TEMPLATE_ID=$(aws ssm get-parameter --name "/prod/spicyportfolio/emailjs/template-id" --query "Parameter.Value" --output text)
                SERVICE_ID=$(aws ssm get-parameter --name "/prod/spicyportfolio/emailjs/service-id" --query "Parameter.Value" --output text)
                PUBLIC_KEY=$(aws ssm get-parameter --name "/prod/spicyportfolio/emailjs/public-key" --query "Parameter.Value" --output text)

                echo "VITE_APP_EMAILJS_TEMPLATE_ID=$TEMPLATE_ID" >> $GITHUB_ENV
                echo "VITE_APP_EMAILJS_SERVICE_ID=$SERVICE_ID" >> $GITHUB_ENV
                echo "VITE_APP_EMAILJS_PUBLIC_KEY=$PUBLIC_KEY" >> $GITHUB_ENV

            - name: Build project
              run: npm run build

            - name: Deploy to S3
              run: |
                  aws s3 sync ./dist s3://spicyportfolio --delete
